let buttonColors = ["red", "blue", "green", "yellow"];   
let gamePattern = [];  // To store the selected color
let userClickedPattern = [];  // To store the buttons that got clicked
let level = 0;    // Track the number of level 


// Keep track of whether if the game has started or not, so you only call nextSequence() on the first keypress.
let gameStart = false;
$(document).on("keydown", function(){
    if(gameStart === false)   // The game hasn't started yet
    {
        console.log("The key was pressed");
        $("#level-title").text("Level " + level);
        nextStep();
        gameStart = true;  /* Ensure that the game starts only once when the key is pressed. 
                              Without it, pressing another key would reset the game back to "Level 0" */
    }
});

// Create a handler function to detect when any of the buttons are clicked
$(".btn").on("click", function(){
    // Store the id of the button that got clicked
    let userChosenColor = $(this).attr("id");
    userClickedPattern.push(userChosenColor);      // Store the clicked buttons into an empty array

    console.log("Clicked by user: " + userClickedPattern); 
    playSound(userChosenColor);    // Play the sound for the corresponding button that is clicked
    animatePress(userChosenColor);  // Animate the button that is clicked by the user
    checkAnswer(userClickedPattern.length-1);  // Get the index number of the last clicked color and compare with the one that was generated

    //console.log("The last index that was clicked is: " + checkAnswer(userClickedPattern.length-1));
});

function nextStep (){
    /* Reset the userClickedPattern to an empty array, ready for the next level 
       because as the game starts immediately after the user clicked the generated button 
    */
    userClickedPattern = [];     

    level++;  // increase the level every time nextStep() is called.
    let randomNumber = Math.floor(Math.random() * 4);     // Creating a random number from 0 to 3 (for each button)
    let randomChosenColor = buttonColors[randomNumber];   // Select a random color from the generated numbers
    gamePattern.push(randomChosenColor);                  // Store the random selected color into an empty array
    console.log("Random color that is generated by gamePattern is: " + gamePattern);

    // Animate the selected button from each button with CSS ID's to seem like it was pressed/makes it flash
    $("#" + randomChosenColor).fadeIn(1000).fadeOut(100).fadeIn(100); 
    $("#level-title").text("Level " + level);
    playSound(randomChosenColor);  // Play the sound for the corresponding button that is randomly choose   
}

function playSound(soundName) {
    let sound = new Audio("sounds/" + soundName + ".mp3");
    sound.play();
}

function animatePress(currentColor) {
    // Add pressed class from CSS to the button that gets clicked
    $("#" + currentColor).addClass("pressed");
    setTimeout(function(){
        // in 140 ms will remove the pressed class that has a box-shadow element applied over the button that is pressed
        $("#" + currentColor).removeClass("pressed");  
    }, 140);
}

function checkAnswer(currentLevel){
    // Check if the most recent user answer is the same as the gamePattern (the generated button)
    if(gamePattern[currentLevel] === userClickedPattern[currentLevel])
    {
        console.log("It is the same");
        // If the user got the most recent answer right, then check 
        if(userClickedPattern.length === gamePattern.length)
        {
            console.log("Success");
            //call nextStep() after 1000 ms delay
            setTimeout(function(){
                nextStep();
            }, 1000); 
        }
    }
    else {
        console.log("Fail");
        playSound("wrong");

        //When a button is clicked and it is not the right button, the background will be red for 200ms
        $("body").addClass("game-over");    
        setTimeout(function(){
            $("body").removeClass("game-over");
        }, 200);
        $("#level-title").text("Game Over, Press Any Key to Restart");
        startOver();    // Reset the game if it is over
    }
}

// Reset the level, the random color and the gameStart
function startOver(){
    level = 0;
    gamePattern = []; 
    gameStart = false; 
}